# Generated by Django 4.2.13 on 2024-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentadvertisement',
            name='amenities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentadvertisement',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentadvertisement',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
