# Generated by Django 5.0.6 on 2024-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_rentadvertisement_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentadvertisement',
            name='image',
            field=models.ImageField(null=True, upload_to='advertisement/images/'),
        ),
    ]
